config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  root 'users#index'
  resources 'users'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(name: params[:name].downcase)
    if user && user.authenticate(params[:password])
      log_in user
      redirect_to user
    else
      render 'new'
    end
  end
  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in user
      redirect_to root_path
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.required(:user).permit(:name, :password, :password_confirmation)
  end
    
end

app/helpers/.#sessions_helper.rb
wata@wata-FMVU7B3WDB.7526:1560758108

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end 
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStudy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>TOP</h1>


<% @users.each do |user| %>
<%= link_to user.name, user_path(user) %>
<% end %>
<% if logged_in? %>
 <p>current user is</p><%= @current_user.name %>
 <%= link_to "Log out", logout_path, method: "delete" %>
<% else %>
 <%= link_to "新規登録", new_user_path %>
 <%= link_to "Log in", login_path %>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= form_with model: @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :password%>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>User <%= @user.id %></h1>

<%= @user.name %>

 <%= link_to "Log out", logout_path, method: "delete" %>
 <%= link_to "top", root_path %>